"use client"

import { FileText, Printer } from "lucide-react"

import { Button } from "@/components/ui/button"

export type DerivedReportSection = {
  heading: string
  body?: string
  items?: { label: string; detail: string; tone?: "normal" | "warn" | "good" }[]
}

export function DerivedReport({ title, description, matterName, matterNumber, sections }: { title: string; description: string; matterName: string; matterNumber: string; sections: DerivedReportSection[] }) {
  return <div className="space-y-6 pb-16"><div className="rounded-2xl bg-[#23313d] p-6 text-white print:bg-white print:p-0 print:text-black"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#d5a083] print:text-[#a24f31]">MatterPilot report</p><h1 className="mt-2 font-serif text-3xl font-semibold">{title}</h1><p className="mt-2 text-sm text-[#b9c5ca] print:text-gray-600">{matterName} · {matterNumber}</p></div><FileText className="size-7 text-[#d5a083] print:hidden" /></div><p className="mt-5 max-w-3xl text-sm leading-6 text-[#d6dfe2] print:text-gray-700">{description}</p></div><div className="flex items-center justify-between gap-3 print:hidden"><p className="text-xs text-[#8b8d88]">Derived from the records currently available in this matter.</p><Button onClick={() => window.print()} variant="outline" className="border-[#ded9d0] bg-white text-[#39443f]"><Printer /> Print report</Button></div><div className="space-y-5">{sections.map((section) => <section key={section.heading} className="rounded-2xl border border-[#ded9d0] bg-[#fbfaf7] p-5 shadow-sm print:rounded-none print:bg-white print:p-0 print:shadow-none"><h2 className="font-serif text-xl font-semibold text-[#23313d]">{section.heading}</h2>{section.body ? <p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-[#59645e]">{section.body}</p> : null}{section.items?.length ? <div className="mt-4 space-y-2">{section.items.map((item, index) => <div key={`${item.label}-${index}`} className="rounded-xl border border-[#e8e3da] bg-white p-3 print:rounded-none"><div className="flex flex-wrap items-start justify-between gap-2"><p className="text-sm font-semibold text-[#39443f]">{item.label}</p>{item.tone ? <span className={item.tone === "warn" ? "rounded-full bg-amber-50 px-2 py-1 text-[10px] font-bold text-amber-800" : item.tone === "good" ? "rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-bold text-emerald-700" : "rounded-full bg-[#f1eee8] px-2 py-1 text-[10px] font-bold text-[#737872]"}>{item.tone === "warn" ? "Needs review" : item.tone === "good" ? "Covered" : "Recorded"}</span> : null}</div><p className="mt-1 text-xs leading-5 text-[#737872]">{item.detail}</p></div>)}</div> : null}</section>)}</div><p className="text-xs leading-5 text-[#8b8d88] print:mt-6">Limitations: this report is a structured view of records entered in MatterPilot. It does not make legal conclusions, authenticate evidence, calculate binding legal deadlines, or replace attorney review.</p></div>
}
